### ISSUE TITLE
/jobs/new - add support for displaying metadata from manifest.yml in template directories to support creating Ruby cluster specific templates

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-myjobs#16]
A template should be able to provide a manifest.yml file containing information like:

``` yaml
name: Abaqus 6.14
cluster: oak-batch.osc.edu
notes: Uses: module load abaqus/6.14-nimbis
```

or

``` yaml
name: Abaqus 6.14
cluster: ruby
notes: Uses: module load abaqus/6.14-nimbis
```

Then this would appear in the template and the specified cluster would be used, providing support for Ruby templates.

This would be scraped and pulled similar to how the apps list for users is built by the dashboard - by reading the manifest.yml files for each of the templates. At this point a database column for templates could become useful for **caching this information** which might mean a list of the directories AND timestamps on the manifests that you cache, but caching in the database to speed this up (or providing another datastore for this cache) is a **separate issue**.

The point of this non-database approach to this information is that the cache never gets "outdated" - we can add new templates and remove old ones from the templates directory and all users of the app are ensured to always have the latest list of templates.
